server:
  port: 8080

spring:
  shardingsphere:
    # 打印sql
    props:
      sql:
        show: true
    datasource:
      names: ds0, ds1
      # 主库
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_0?characterEncoding=utf-8&serverTimezone=GMT
        username: root
        password: root
      # 从库,可以配置多个这里只配置了一个
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:
        url: jdbc:mysql://localhost:3306/demo_ds_0?characterEncoding=utf-8&serverTimezone=GMT
        username: root
        password: root
    sharding:
      # 按照年龄分库
      default-database-strategy:
        inline:
          sharding-column: age
          algorithm-expression: ds$->{age % 2}
      # 按照id分表
      tables:
        tab_user:
          actual-data-nodes: ds$->{0..1}.tab_user_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: tab_user_$->{id % 2}

