server:
  port: 8080

spring:
  shardingsphere:
    masterslave:
      name: master-slave
      master-data-source-name: master
      slave-data-source-names: slave0
      load-balance-algorithm-type: round_robin
    datasource:
      names: master, slave0
      # 主库
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master_user?characterEncoding=utf-8&serverTimezone=GMT
        username: root
        password: root
      # 从库,可以配置多个这里只配置了一个
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:
        url: jdbc:mysql://localhost:3306/slave_user?characterEncoding=utf-8&serverTimezone=GMT
        username: root
        password: root